using Il2CppInterop.Runtime.InteropTypes;
using Il2CppInterop.Runtime.InteropTypes.Stores;

namespace Il2CppInterop.Runtime;

/// <summary>
/// Methods only used by assemblies generated by Il2CppInterop.Generator
/// </summary>
internal unsafe class Il2CppCodeGen
{
    internal static void EnsureValueTypeSize<T>() where T : unmanaged
    {
        var expected = Il2CppClassPointerStore<T>.Pointer->ValueSize;
        var actual = sizeof(T);

        if (expected != actual)
        {
            throw new InvalidOperationException($"Type {typeof(T).FullName} has a different size ({actual}) than expected ({expected}). This is probably a bug in Il2CppInterop.Generator, please report it there.");
        }
    }
}
